Repository fako1024/gotools, pull requests merged in 2024-06, with the labels that each got.

#8 Provide additional interface methods for io.ReadWriter compliant memory pool elements
  concurrency/mempool.go
  concurrency/mempool_test.go
  concurrency/readwriter.go
Labels: enhancement

#10 Add safeguards against invalid input in Unpack routines
  bitpack/bitpack.go
  bitpack/bitpack_test.go
Labels: bug

#12 Add Close() method for three-point lock to support channel cleanup
  concurrency/threepointlock.go
  concurrency/threepointlock_test.go
Labels: bug, enhancement

#13 [fetaure] Add encoder/decoder chain implementation
  concurrency/encoding.go
  concurrency/encoding_test.go
  concurrency/go.mod
  concurrency/go.sum
  concurrency/mempool.go
  concurrency/readwriter.go
Labels: enhancement
